version: '3.3'

services:
  mariadb:
    image: mariadb:10.6
    ports:
      - 3307:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./storage/mariadb:/var/lib/mysql
      - ./mariadb/init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=travel-root
