name: Build and deploy travel-java-backend-monolith-sonic

on:
  push:
    branches: [ master ]
    paths-ignore: ['**/workflows/**']
  workflow_dispatch:
  
jobs:
  build: 
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
    - name: Checkout travel-java-backend-monolith-sonic repo
      uses: actions/checkout@v3
      with: 
        ref: 'master'
    - name: Cache layer for Docker
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}
    - name: Build Docker image
      run: docker build -t $DOCKERHUB_REPO:latest -t $DOCKERHUB_REPO:${GITHUB_SHA::8} .
    - name: Publish Docker image
      run: docker push $DOCKERHUB_REPO
  deploy:
    name: Deploy docker image
    # runs-on: ubuntu-latest
    # needs: build
    # steps:
    # - name: Deploy docker container webhook
      # uses: joelwmale/webhook-action@master
      # env:
        # WEBHOOK_URL: ${{ secrets.DEPLOY_URL_SONIC  }}
