name: Build and deploy travel-java-backend-monolith-sonic

on:
  push:
    branches: [ master ]
    paths-ignore: ['**/workflows/**']
  workflow_dispatch:
  
jobs:
  build: 
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
    - name: Checkout travel-java-backend-monolith-sonic repo
      uses: actions/checkout@v3
      with: 
        ref: 'master'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Compile
      run: mvn -B compile --file pom.xml
    - name: Build a package
      run: mvn -B package --file pom.xml  -DskipTests
    - name: Temporarily save jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/travel/target/travel.jar
        retention-days: 1
      
  deploy:
    runs-on: ubuntu-18.04
    needs: build

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
          name: jar-artifact
          path: target/        
    - name: Build Docker image
      run: docker build -t $DOCKERHUB_REPO:latest -t $DOCKERHUB_REPO:${GITHUB_SHA::8} .      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}
    - name: Publish Docker image
      run: docker push $DOCKERHUB_REPO
      
  #run:
    # name: Deploy docker image
    # runs-on: ubuntu-latest
    # needs: build
    # steps:
    # - name: Deploy docker container webhook
      # uses: joelwmale/webhook-action@master
      # env:
        # WEBHOOK_URL: ${{ secrets.DEPLOY_URL_SONIC  }}
